[package]
name = "hyper_serde"
version = "0.2.0"
authors = ["Anthony Ramine <n.oxyde@gmail.com>"]
description = "Serde support for Hyper types"
license = "MIT"
repository = "https://github.com/nox/hyper_serde"

[lib]
doctest = false

[dependencies]
cookie = {version = "0.4", default-features = false}
hyper = {version = "0.10", default-features = false}
mime = {version = "0.2.2", features = ["serde"]}
serde = "0.8"

[dev-dependencies]
serde_test = "0.8"
